package com.trimc.blogger.commons.type;

public enum QuestionCategoryUpperType {

	CommonGround("Common Ground", "asked when the questioner wants to establish or confirm whether knowledge is shared between participants in the conversation "),

	ConversationControl("Conversation Control", "asked to manipulate the flow of conversation or the attention of the speech participants"),

	KnowledgeDeficit("knowledge Deficit", "generated by a person's knowledge deficits and cognitive disequilibrium"),

	SocialCoordination("Social Coordination", "indirect requests for the addressee to perform an action ");

	private String name;

	private String overview;

	private QuestionCategoryUpperType(String name, String overview) {
		setName(name);
		setOverview(overview);
	}

	public String description() {
		return getOverview();
	}

	private String getName() {
		return name;
	}

	private String getOverview() {
		return overview;
	}

	private void setName(String name) {
		this.name = name;
	}

	private void setOverview(String overview) {
		this.overview = overview;
	}

	@Override
	public String toString() {
		return getName();
	}

}
